# -*- coding: utf-8 -*-
"""analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3JMt3Cbn5TIL9t7XCifyoAuRljwRL-Z
"""

import numpy as np

def analyze(grades):
    grades = np.array(grades)

    result = {
        "average": np.mean(grades),
        "passed": grades[grades >= 50],
        "failed": grades[grades < 50],
        "excellent": grades[grades >= 85],
        "max": np.max(grades),
        "min": np.min(grades),
    }

    return result