# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LH3TBB264aKs_-cqacsZOZi8Kww8_xUZ
"""

from analyzer_py import analyze

grades = [45, 67, 89, 90, 33, 72, 58, 100, 61]

report = analyze(grades)

print(" Student Report")
print("Average:", report["average"])
print("Passed:", report["passed"])
print("Failed:", report["failed"])
print("Excellent:", report["excellent"])
print("Max:", report["max"])
print("Min:", report["min"])